### ISSUE TITLE
UnknownCurrencyException [currencyCode=EUR]

### ISSUE THREAD

**Issue by MeiSign** [sphereio/sphere-jvm-sdk#264]
We try to create products with this attributes:
 
Imports:

    import common.domain.{OfferDraft, DemandDraft}
    import common.helper.Configloader
    import io.sphere.sdk.attributes._
    import io.sphere.sdk.models.{DefaultCurrencyUnits, LocalizedStrings}
    import io.sphere.sdk.producttypes.ProductTypeDraft
    import io.sphere.sdk.utils.MoneyImpl
    import scala.collection.JavaConverters._

Code that throws the exception:

    def buildDemandAttributes(demandDraft: DemandDraft) = List(
        Attribute.of("userId", demandDraft.uid.value),
        Attribute.of("mustTags", demandDraft.mustTags.mkString(";")),
        Attribute.of("shouldTags", demandDraft.shouldTags.mkString(";")),
        Attribute.of("longitude", demandDraft.location.lon.value),
        Attribute.of("latitude", demandDraft.location.lat.value),
        Attribute.of("distance", demandDraft.distance.value),
        Attribute.of("priceMin", MoneyImpl.of(BigDecimal(demandDraft.priceMin.value).bigDecimal, DefaultCurrencyUnits.EUR)),
        Attribute.of("priceMax", MoneyImpl.of(BigDecimal(demandDraft.priceMax.value).bigDecimal, DefaultCurrencyUnits.EUR))
      ).asJava

And this leads to this exception:
    
    java.lang.ExceptionInInitializerError
    at common.sphere.ProductTypeDrafts$.buildDemandAttributes(ProductTypeDrafts.scala:25)
    at services.DemandService.writeDemandToSphere(DemandService.scala:66)
    at services.DemandService.createDemand(DemandService.scala:28)
    at migrations.ProductTestDataMigrations$$anonfun$createDemands$1.apply(ProductTestDataMigrations.scala:49)
    at migrations.ProductTestDataMigrations$$anonfun$createDemands$1.apply(ProductTestDataMigrations.scala:49)
    at scala.collection.immutable.List.map(List.scala:272)
    at migrations.ProductTestDataMigrations.createDemands(ProductTestDataMigrations.scala:49)
    at migrations.ProductTestDataMigrations$$anonfun$1.apply(ProductTestDataMigrations.scala:30)
    at migrations.ProductTestDataMigrations$$anonfun$1.apply(ProductTestDataMigrations.scala:22)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    Caused by: UnknownCurrencyException [currencyCode=EUR]
    at javax.money.spi.MonetaryCurrenciesSingletonSpi.getCurrency(MonetaryCurrenciesSingletonSpi.java:74)
    at javax.money.MonetaryCurrencies.getCurrency(MonetaryCurrencies.java:73)
    at io.sphere.sdk.models.DefaultCurrencyUnits.<clinit>(DefaultCurrencyUnits.java:10)

Are we using the MoneyImpl wrong or is this a known bug? 
I can't figure out how can cause this error because we have no influence on how the MonetaryCurrencies are initialized...

**Comment by MeiSign** [comment]
I just found out that it works if I don't use DefaultCurrencyUnits.EUR but the String "EUR"

    def buildDemandAttributes(demandDraft: DemandDraft) = List(
      Attribute.of("userId", demandDraft.uid.value),
      Attribute.of("mustTags", demandDraft.mustTags.mkString(";")),
      Attribute.of("shouldTags", demandDraft.shouldTags.mkString(";")),
      Attribute.of("longitude", demandDraft.location.lon.value),
      Attribute.of("latitude", demandDraft.location.lat.value),
      Attribute.of("distance", demandDraft.distance.value),
      Attribute.of("priceMin", MoneyImpl.of(BigDecimal(demandDraft.priceMin.value).bigDecimal, "EUR")),
      Attribute.of("priceMax", MoneyImpl.of(BigDecimal(demandDraft.priceMax.value).bigDecimal, "EUR"))
    ).asJava

**Comment by schleichardt** [comment]
The underlying money library initializes in a weird way so that the same code results in different results. So I refactored the DefaultCurrencyUnit creation to be like the money thing and updated the money library.

**Comment by schleichardt** [comment]
Is the issue solved for you?

**Comment by MeiSign** [comment]
We are still using the String Parameter so it is working right now but I am not sure if the issue is solved.

**Comment by schleichardt** [comment]
I can't reproduce and Java Money has new releases so I close the ticket.
