### ISSUE TITLE
Deserializing of enum and localized enum attributes

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#276]
It is not possible to deserialize the enum values as expected:

```
final LocalizedEnumValue localizedEnumValue =
                LocalizedEnumValue.of("key1", LocalizedStrings.ofEnglishLocale("value1"));

final AttributeGetterSetter<Product, LocalizedEnumValue> getterSetter =
                AttributeAccess.ofLocalizedEnumValue().ofName("attributeName");
final Attribute attribute = Attribute.of(getterSetter, localizedEnumValue);
final LocalizedEnumValue value = attribute.getValue(getterSetter.getMapper());
                /*
io.sphere.sdk.attributes.AttributeMappingException: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class io.sphere.sdk.models.LocalizedEnumValue] from String value ('key1'); no single-String constructor/factory method
[error]  at [Source: N/A; line: -1, column: -1], took 0.417 sec
[error]     at io.sphere.sdk.attributes.AttributeMapperImpl.deserialize(AttributeMapperImpl.java:26)
[error]     at io.sphere.sdk.attributes.AttributeImpl.getValue(AttributeImpl.java:30)
[error]     at io.sphere.sdk.producttypes.EnumProbTest.testName(EnumProbTest.java:18)
[error]     ...
[error] Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class io.sphere.sdk.models.LocalizedEnumValue] from String value ('key1'); no single-String constructor/factory method
[error]  at [Source: N/A; line: -1, column: -1]
[error]     at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
[error]     at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:757)
[error]     at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:277)
[error]     at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:289)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1133)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:135)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
[error]     at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
[error]     at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:971)
[error]     at io.sphere.sdk.attributes.AttributeMapperImpl.deserialize(AttributeMapperImpl.java:24)
[error]     ... 58 more
         */
    }
```

The SPHERE.IO API does only return the key for a (localized) enum so the values are not available.
In combination with the product type it is maybe possible to construct the localized enum value.

There is a workaround for now to read the key as String:

```
//a localized enum value
final LocalizedEnumValue localizedEnumValue =
        LocalizedEnumValue.of("key1", LocalizedStrings.ofEnglishLocale("value1"));

//this creates an attribute like the HTTP should return
//if you print the attribute, you will see, that there is a data loss
final AttributeGetterSetter<Product, LocalizedEnumValue> getterSetter =
        AttributeAccess.ofLocalizedEnumValue().ofName("attributeName");
final Attribute attribute = Attribute.of(getterSetter, localizedEnumValue);

//workaround: read the key of the localized enum as String:
final AttributeMapper<String> stringAttributeMapper = AttributeMapper.of(TypeReferences.stringTypeReference());
final String value = attribute.getValue(stringAttributeMapper);
assertThat(value).isEqualTo("key1");
```

**Comment by mfriess2** [comment]
Is there also a workaround available for a set of enums? Because then the String Mapper does not seem work.

**Comment by schleichardt** [comment]
Yes

```
        final LocalizedEnumValue v1 = LocalizedEnumValue.of("key1", LocalizedStrings.ofEnglishLocale("value1"));
        final LocalizedEnumValue v2 = LocalizedEnumValue.of("key2", LocalizedStrings.ofEnglishLocale("value2"));


        final AttributeGetterSetter<Product, Set<LocalizedEnumValue>> getterSetter =
                AttributeAccess.ofLocalizedEnumValueSet().ofName("attributeName");
        final Attribute attribute = Attribute.of(getterSetter, asSet(v1, v2));

        final AttributeMapper<Set<String>> stringSetAttributeMapper =
                AttributeMapper.of(new TypeReference<Set<String>>() { });
        final Set<String> values = attribute.getValue(stringSetAttributeMapper);
        assertThat(values).containsOnly("key1", "key2");
```

**Comment by schleichardt** [comment]
fixed in PR https://github.com/sphereio/sphere-jvm-sdk/pull/465

see https://github.com/sphereio/sphere-jvm-sdk/commit/396faf45b4b095dd4a4fa01e0ba4ff39f2d7c760#diff-64126202779bb79e222e172b6b88f463R30
