### ISSUE TITLE
Compatibility issues with Jackson 2.5.1

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#312]
```
===== BEGIN EXCEPTION OUTPUT =====
SDK: 1.0.0-M12-2015-03-10-13-52-25-ff86006-SNAPSHOT
project: <unknown>
Java: 1.8.0_20
cwd: /Users/lauraluiz/dev/src/sphere-lightspeed
date: Wed Mar 18 14:25:20 CET 2015
sphere request: <unknown>
http request: <unknown>
http response: <unknown>
detailMessage: Cannot parse {"offset":0,"count":1,"total":15,"results":[{"masterVariant":{"id":1,"sku":"2","prices":[{"value":{"currencyCode":"EUR","centAmount":1413}}],"images":[{"url":"https://s3.eu-central-1.amazonaws.com/commercetools-angry-bird-demo/Red+Skywalker+Plush+Toy.jpg","dimensions":{"w":0,"h":0}}],"attributes":[{"name":"size","value":{"key":"onesize","label":"one size"}},{"name":"color","value":{"key":"multicolor","label":"multi color"}}]},"id":"184aaadc-63f6-4e6a-95fe-22b4f001612f","version":2,"productType":{"typeId":"product-type","id":"371e1d3a-e553-4b76-a834-dd3745c9afa0"},"name":{"en":"Red Skywalker Plush Toy"},"description":{"en":"Red Skywalker is a committed Rebel and is learning to be a Jedi Bird warrior."},"categories":[{"typeId":"category","id":"bc67f617-79ca-4f48-bf1b-18d5dbc7b552"}],"slug":{"en":"Red-Skywalker-Plush-Toy"},"metaTitle":{"en":"Red Skywalker Plush Toy"},"metaKeywords":{"en":"star wars, toy, angry birds"},"metaDescription":{"en":"Red Skywalker is a committed Rebel and is learning to be a Jedi Bird warrior."},"variants":[],"searchKeywords":{},"hasStagedChanges":false,"published":true,"taxCategory":{"typeId":"tax-category","id":"ab3939bd-0e2d-4fbb-a640-ae8a33c4e2c9"},"createdAt":"2015-02-25T11:20:11.466Z","lastModifiedAt":"2015-02-25T11:20:11.687Z"}],"facets":{}}
Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/1.0.0-M12-2015-03-10-13-52-25-ff86006-SNAPSHOT/io/sphere/sdk/json/JsonException.html
===== END EXCEPTION OUTPUT =====
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205)
	at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:723)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
	at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:723)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2345)
	at io.sphere.sdk.client.NingHttpClientAdapterImpl.lambda$wrap$6(NingHttpClientAdapterImpl.java:94)
	at io.sphere.sdk.client.NingHttpClientAdapterImpl$$Lambda$70/1886701598.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.sphere.sdk.json.JsonException:
===== BEGIN EXCEPTION OUTPUT =====
SDK: 1.0.0-M12-2015-03-10-13-52-25-ff86006-SNAPSHOT
project: <unknown>
Java: 1.8.0_20
cwd: /Users/lauraluiz/dev/src/sphere-lightspeed
date: Wed Mar 18 14:25:20 CET 2015
sphere request: <unknown>
http request: <unknown>
http response: <unknown>
detailMessage: Cannot parse {"offset":0,"count":1,"total":15,"results":[{"masterVariant":{"id":1,"sku":"2","prices":[{"value":{"currencyCode":"EUR","centAmount":1413}}],"images":[{"url":"https://s3.eu-central-1.amazonaws.com/commercetools-angry-bird-demo/Red+Skywalker+Plush+Toy.jpg","dimensions":{"w":0,"h":0}}],"attributes":[{"name":"size","value":{"key":"onesize","label":"one size"}},{"name":"color","value":{"key":"multicolor","label":"multi color"}}]},"id":"184aaadc-63f6-4e6a-95fe-22b4f001612f","version":2,"productType":{"typeId":"product-type","id":"371e1d3a-e553-4b76-a834-dd3745c9afa0"},"name":{"en":"Red Skywalker Plush Toy"},"description":{"en":"Red Skywalker is a committed Rebel and is learning to be a Jedi Bird warrior."},"categories":[{"typeId":"category","id":"bc67f617-79ca-4f48-bf1b-18d5dbc7b552"}],"slug":{"en":"Red-Skywalker-Plush-Toy"},"metaTitle":{"en":"Red Skywalker Plush Toy"},"metaKeywords":{"en":"star wars, toy, angry birds"},"metaDescription":{"en":"Red Skywalker is a committed Rebel and is learning to be a Jedi Bird warrior."},"variants":[],"searchKeywords":{},"hasStagedChanges":false,"published":true,"taxCategory":{"typeId":"tax-category","id":"ab3939bd-0e2d-4fbb-a640-ae8a33c4e2c9"},"createdAt":"2015-02-25T11:20:11.466Z","lastModifiedAt":"2015-02-25T11:20:11.687Z"}],"facets":{}}
Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/1.0.0-M12-2015-03-10-13-52-25-ff86006-SNAPSHOT/io/sphere/sdk/json/JsonException.html
===== END EXCEPTION OUTPUT =====
	at io.sphere.sdk.client.SphereClientImpl.parse(SphereClientImpl.java:88)
	at io.sphere.sdk.client.SphereClientImpl.lambda$preProcess$24(SphereClientImpl.java:73)
	at io.sphere.sdk.client.SphereClientImpl$$Lambda$115/1434383474.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:717)
	... 13 more
Caused by: io.sphere.sdk.json.JsonException:
===== BEGIN EXCEPTION OUTPUT =====
SDK: 1.0.0-M12-2015-03-10-13-52-25-ff86006-SNAPSHOT
project: <unknown>
Java: 1.8.0_20
cwd: /Users/lauraluiz/dev/src/sphere-lightspeed
date: Wed Mar 18 14:25:20 CET 2015
sphere request: <unknown>
http request: <unknown>
http response: <unknown>
detailMessage: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class io.sphere.sdk.models.ImageImpl]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: [B@5345e22f; line: 1, column: 153] (through reference chain: java.util.ArrayList[0]->java.util.ArrayList[0])
Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/1.0.0-M12-2015-03-10-13-52-25-ff86006-SNAPSHOT/io/sphere/sdk/json/JsonException.html
===== END EXCEPTION OUTPUT =====
	at io.sphere.sdk.json.JsonUtils.readObject(JsonUtils.java:117)
	at io.sphere.sdk.client.SphereRequestBase.lambda$resultMapperOf$4(SphereRequestBase.java:22)
	at io.sphere.sdk.client.SphereRequestBase$$Lambda$38/969504439.apply(Unknown Source)
	at io.sphere.sdk.client.SphereClientImpl.parse(SphereClientImpl.java:85)
	... 16 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class io.sphere.sdk.models.ImageImpl]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: [B@5345e22f; line: 1, column: 153] (through reference chain: java.util.ArrayList[0]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1080)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2688)
	at io.sphere.sdk.json.JsonUtils.readObject(JsonUtils.java:115)
	... 19 more
```

**Comment by schleichardt** [comment]
@lauraluiz Can you please retry with version "1.0.0-M12-SNAPSHOT"?

**Comment by lauraluiz** [comment]
@schleichardt it works!

**Comment by schleichardt** [comment]
Every entity which needs to be deserialized needs the JsonCreator annotation. 
 https://github.com/FasterXML/jackson-module-parameter-names#usage-example
