### ISSUE TITLE
[1.0.0-M13] CustomerSignInCommand returns empty ErrorResponseException

### ISSUE THREAD

**Issue by MeiSign** [sphereio/sphere-jvm-sdk#397]
We receive an empty ErrorResponseException when we run a CustomerSignInCommand. From what I can say we use the command correctly and use a valid email address and password as  parameters but it is hard to debug because of the cryptic exception.
Is it possible that this command is broken since one of the last releases? We think that this command did work and we have not changed our code except updating the sphere dependencies.

Code:

    def sphereSignIn(credentials: UserCredentials): Future[Boolean] = {
        println(s"${credentials.email.value}:${credentials.password.value}")
        val signInQuery = CustomerSignInCommand.of(
            credentials.email.value, credentials.password.value)

        sphereClient.execute(signInQuery)
            .map(_ => true)
            .recover {
              case e: Exception =>
                throw e
                false 
            }
    }

 Exception:

    [error] play - Cannot invoke the action, eventually got an error: java.util.concurrent.CompletionException: io.sphere.sdk.client.ErrorResponseException: SDK: 1.0.0-M13
    project: <unknown>
    Java: 1.8.0_45
    cwd: /Users/Stefan/Workspace/Scala/neeedo-api
    date: Wed May 06 23:09:48 CEST 2015
    sphere request: <unknown>
    http request: <unknown>
    http response: <unknown>
    additional notes: []
    Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M13/io/sphere/sdk/client/ErrorResponseException.html

    [error] application -  ! @6m442ffmf - Internal server error, for (POST) [/offers] ->

    play.api.Application$$anon$1: Execution exception[[CompletionException: io.sphere.sdk.client.ErrorResponseException: SDK: 1.0.0-M13
    project: <unknown>
    Java: 1.8.0_45
    cwd: /Users/Stefan/Workspace/Scala/neeedo-api
    date: Wed May 06 23:09:48 CEST 2015
    sphere request: <unknown>
    http request: <unknown>
    http response: <unknown>
    additional notes: []
    Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M13/io/sphere/sdk/client/ErrorResponseException.html
    ]]
	    at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
	    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
	    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
	    at scala.Option.map(Option.scala:146) [scala-library-2.11.6.jar:na]
    Caused by: java.util.concurrent.CompletionException: io.sphere.sdk.client.ErrorResponseException: SDK: 1.0.0-M13
    project: <unknown>
    Java: 1.8.0_45
    cwd: /Users/Stefan/Workspace/Scala/neeedo-api
    date: Wed May 06 23:09:48 CEST 2015
    sphere request: <unknown>
    http request: <unknown>
    http response: <unknown>
    additional notes: []
    Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M13/io/sphere/sdk/client/ErrorResponseException.html

	    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_45]
	    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_45]
	    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[na:1.8.0_45]
	    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_45]
	    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_45]
    Caused by: io.sphere.sdk.client.ErrorResponseException: SDK: 1.0.0-M13
    project: <unknown>
    Java: 1.8.0_45
    cwd: /Users/Stefan/Workspace/Scala/neeedo-api
    date: Wed May 06 23:09:48 CEST 2015
    sphere request: <unknown>
    http request: <unknown>
    http response: <unknown>
    additional notes: []
    Javadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M13/io/sphere/sdk/client/ErrorResponseException.html

	    at io.sphere.sdk.customers.commands.CustomerSignInCommand.deserialize(CustomerSignInCommand.java:72) ~[sphere-models-1.0.0-M13.jar:1.0.0-M13]
	    at io.sphere.sdk.customers.commands.CustomerSignInCommand.deserialize(CustomerSignInCommand.java:28) ~[sphere-models-1.0.0-M13.jar:1.0.0-M13]
	    at io.sphere.sdk.client.SphereClientImpl.parse(SphereClientImpl.java:89) ~[sphere-java-client-core-1.0.0-M13.jar:1.0.0-M13]
	    at io.sphere.sdk.client.SphereClientImpl.lambda$preProcess$51(SphereClientImpl.java:78) ~[sphere-java-client-core-1.0.0-M13.jar:1.0.0-M13]
	    at io.sphere.sdk.client.SphereClientImpl$$Lambda$387/758912232.apply(Unknown Source) ~[na:na]

**Comment by schleichardt** [comment]
No, I can't remember changing the class.
The integration tests work. But I get the same error behaviour when I urlencode the email.
Is this the cause?

Anyway, I will improve the error message.

**Comment by MeiSign** [comment]
The email adress ist not url encoded actually but I will have a close look at our code than. I let you know when I found the bug...
