### ISSUE TITLE
Test io.sphere.sdk.products.search.ProductProjectionSearchTest.canAccessReferenceCustomAttributes failed: java.lang.NullPointerException

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#449]
in branch variant-identifier

```
[error] Test io.sphere.sdk.products.search.ProductProjectionSearchTest.canAccessReferenceCustomAttributes failed: java.lang.NullPointerException: null, took 0.357 sec
[error]     at java.util.Objects.requireNonNull(Objects.java:203)
[error]     at java.util.Optional.<init>(Optional.java:96)
[error]     at java.util.Optional.of(Optional.java:108)
[error]     at io.sphere.sdk.products.ProductImpl.<init>(ProductImpl.java:24)
[error]     at io.sphere.sdk.products.ProductBuilder.build(ProductBuilder.java:48)
[error]     at io.sphere.sdk.products.search.ProductProjectionSearchTest.product(ProductProjectionSearchTest.java:209)
[error]     at io.sphere.sdk.products.search.ProductProjectionSearchTest.canAccessReferenceCustomAttributes(ProductProjectionSearchTest.java:161)
[error]     ...
```

**Comment by schleichardt** [comment]
currently not failing
