### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: io/sphere/sdk/json/SphereJsonUtils

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#640]
possible bug:

```
[INFO]  at io.sphere.sdk.client.SphereClientImpl.<init>(SphereClientImpl.java:21)
[INFO]  at io.sphere.sdk.client.SphereClientImpl.of(SphereClientImpl.java:131)
[INFO]  at io.sphere.sdk.client.SphereClient.of(SphereClient.java:37)
[INFO]  at io.sphere.sdk.client.SphereClientFactory.createClient(SphereClientFactory.java:42)
[INFO]  at io.sphere.sdk.client.SphereClientFactory.createClient(SphereClientFactory.java:69)
[...]
[INFO]  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO]  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO]  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[INFO]  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
[INFO]  ... 28 more
```

But in https://github.com/schleichardt/commercetools-platform-jvm-sdk-hello-world it works.

**Comment by schleichardt** [comment]
This bug appeared by the reporter when he mixed the version 1.0.0-M16 with 1.0.0-M15.

**Comment by schleichardt** [comment]
This could be solved by explicitly put the Jackson dependencies into the pom.xml.
