### ISSUE TITLE
Warning on shutdown

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#673]
```
        try(final SphereClient client = factory.createClient(config.getString("projectKey"), config.getString("clientId"), config.getString("clientSecret"))) {
           //doing nothing
        }
```

raises:

```
java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
	at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
	at org.jboss.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
	at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
	at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:781)
	at com.ning.http.client.providers.netty.channel.SslInitializer.connectRequested(SslInitializer.java:48)
	at org.jboss.netty.channel.SimpleChannelDownstreamHandler.handleDownstream(SimpleChannelDownstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.connect(Channels.java:634)
	at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:216)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.connect(NettyRequestSender.java:370)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:282)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:115)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:486)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:508)
	at io.sphere.sdk.http.DefaultAsyncHttpClientAdapterImpl.execute(DefaultAsyncHttpClientAdapterImpl.java:30)
	at io.sphere.sdk.http.DefaultAsyncHttpClientAdapterImpl.execute(DefaultAsyncHttpClientAdapterImpl.java:15)
	at io.sphere.sdk.client.TokensSupplierImpl.get(TokensSupplierImpl.java:49)
	at io.sphere.sdk.client.AuthActor.process(AuthActor.java:53)
	at io.sphere.sdk.client.AuthActor$$Lambda$12/847341759.accept(Unknown Source)
	at io.sphere.sdk.client.Actor$ReceiveBuilder.when(Actor.java:39)
	at io.sphere.sdk.client.AuthActor.receive(AuthActor.java:34)
	at io.sphere.sdk.client.Actor.lambda$tell$3(Actor.java:11)
	at io.sphere.sdk.client.Actor$$Lambda$10/1389241631.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by schleichardt** [comment]
This is okay since the auth actor is killed before the token could be fetched. With a sleep of 200ms the warning does not occur.
